# Site settings
title: ""
email: lmmendes(at)gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://locathost3000.pt" # the base hostname & protocol for your site
twitter_username: lmmendes
github_username:  lmmendes

# Build settings
markdown: redcarpet
